Move lots of intelligence into new share/build script.
This simplfies the shell code in share/rules. It has also moved some
actions out of the bin/userdeb script. We are now much more secure in
terms of never letting sensitive unencrypted data hit the disk.

diff --git a/bin/userdeb b/bin/userdeb
--- a/bin/userdeb
+++ b/bin/userdeb
@@ -29,7 +29,6 @@ my $debian;
 my $conflicts;
 my $manifest;
 my $depends;
-my $spass;
 my $gecos;
 my $shell;
 my $identity;
@@ -38,7 +37,6 @@ my $hostname;
 my $now;
 my @sudoers;
 my @aliases;
-my $crontab;
 
 
 sub usage {
@@ -61,7 +59,6 @@ sub init {
         exit 1;
     }
 
-    $spass     = [getpwnam($user)]->[1];
     $shell     = [getpwnam($user)]->[8];
     $gecos     = [getpwnam($user)]->[6] || "$user Unknown";
     $gecos     =~ s/,+// if ($gecos =~ /,$/);
@@ -70,8 +67,6 @@ sub init {
     $identity  .= "  <$user\@$hostname>";
     $pkg       = 'user-' . $user;
     $debian    = File::Spec->catfile($pkg, 'debian');
-    $crontab   = File::Spec->catfile('/var/spool/cron/crontabs', $user);
-    $crontab   = '' unless (-r $crontab);
     $now       = qx/date -R/;
     chomp($now);
 
@@ -88,30 +83,30 @@ sub init {
     #
     if (! -d $datadir) {
         print STDERR "$me: Initializing $datadir\n";
-        debug("mkdir($datadir)");
+        debug($datadir);
         mkdir($datadir) || die "mkdir: $!";
     }
 
     if (! -e $conflicts) {
-        debug("copy(CONFLICTS,$conflicts)");
+        debug($conflicts);
         copy(CONFLICTS, $conflicts) || die "copy: $!"
     }
 
     if (! -e $depends) {
-        debug("copy(DEPENDS,$depends)");
+        debug($depends);
         copy(DEPENDS, $depends) || die "copy: $!";
     }
 
     if (! -e $manifest) {
-        debug("copy(MANIFEST,$manifest)");
+        debug($manifest);
         copy(MANIFEST, $manifest) || die "copy: $!";
     }
 
     $email_address = '';
     if (-r '/etc/email-addresses') {
         open(FH, '/etc/email-addresses') || die "open: $!"; 
-        debug("/etc/email-addresses");
         while (my $line = <FH>) {
+            chomp($line);
             if ($line =~ /^$user:\s*(.*)\s*$/) {
                 $email_address = $1;
             }
@@ -120,8 +115,8 @@ sub init {
 
     if (-r '/etc/aliases') {
         open(FH, '/etc/aliases') || die "open: $!"; 
-        debug("/etc/aliases");
         while (my $line = <FH>) {
+            chomp($line);
             if ($line =~ /^$user:/) {
                 push(@aliases, $line);
             }
@@ -131,29 +126,16 @@ sub init {
         }
     }
 
-    if (-r '/etc/sudoers') {
-        open(FH, '/etc/sudoers') || die "open: $!"; 
-        debug("/etc/sudoers");
-        while (my $line = <FH>) {
-            if ($line =~ /^$user /) {
-                push(@sudoers, $line);
-            }
-        }
-    }
-
-
     debug(<<EOF
-    user=$user
-    datadir=$datadir
-    spass=$spass
-    shell=$shell
-    gecos=$gecos
-    identity=$identity
-    pkg=$pkg
-    debian=$debian
-    email_address=$email_address
-    aliases=@aliases
-    now=$now
+user            = $user
+datadir         = $datadir
+pkg             = $pkg
+debian          = $debian
+shell           = $shell
+gecos           = $gecos
+identity        = $identity
+email_address   = $email_address
+aliases         = @aliases
 EOF
 ); 
 
@@ -343,25 +325,23 @@ sub debian_postinst {
 case "\$1" in
     configure)
 
-        db_get $pkg/password
-        if [ -n "\$RET" -a "\$RET" != 'false' ]; then
-            echo "\$RET" | /usr/share/$pkg/unlock -s
-        else
-            echo "No decrypt password. Run /usr/share/$pkg/unlock manually." >&2
-        fi
-
-        for path in `dpkg -L $pkg | grep 'home/$user'`; do
-            if [ -e \$path ]; then # run idempotently
-                chown $user:$user \$path
-            fi
-        done
+        # A bit of an attempt to hide which files belong to the user,
+        # although anyone with access to the .deb can figure this out
 
         temp=\$(mktemp)
-        grep -v '/home' /var/lib/dpkg/info/$pkg.list > \$temp
-        chmod 644 \$temp
-        mv \$temp /var/lib/dpkg/info/$pkg.list
+        grep '/usr/share' /var/lib/dpkg/info/$pkg.list > \$temp
+        cat \$temp > /var/lib/dpkg/info/$pkg.list
+        rm \$temp
+
+
+        cront=/var/spool/cron/crontabs/$user.gz.cpt
+        if [ -e \$cront ]; then
+            chmod 600 \$cront
+            chown $user:crontab \$cront
+        fi
 
         if [ -n "$email_address" ]; then
+            echo "Configuring /etc/email-addresses" >&2
             if ! grep '^$user:' /etc/email-addresses > /dev/null 2>&1; then
                 echo '$user: $email_address' >> /etc/email-addresses
             fi
@@ -371,6 +351,7 @@ EOF
 ;
     foreach my $alias (@aliases) {
         print FH <<EOF
+        echo "Configuring /etc/aliases" >&2
         if ! grep '$alias' /etc/aliases > /dev/null 2>&1; then
             echo '$alias' >> /etc/aliases
         fi
@@ -379,19 +360,20 @@ EOF
 ;
     }
 
-    foreach my $sudo (@sudoers) {
-        print FH <<EOF
-        if [ -r /etc/sudoers ]; then
-            if ! grep '$sudo' /etc/sudoers > /dev/null 2>&1; then
-                echo '$sudo' >> /etc/sudoers
-            fi
+    print FH <<EOF
+
+        # decryption is independent from the package system, and this
+        # is the last thing that we do. If the installation is
+        # unattended for whatever reason, or this fails, it can be
+        # re-run manually at a later time.
+
+        db_get $pkg/password
+        if [ -n "\$RET" -a "\$RET" != 'false' ]; then
+            echo "\$RET" | /usr/share/$pkg/unlock -s
+        else
+            echo "No decrypt password. Run /usr/share/$pkg/unlock manually." >&2
         fi
 
-EOF
-;
-    }
-
-    print FH <<EOF
         ;;
     re-configure|abort-upgrade|abort-remove|abort-deconfigure)
 
@@ -439,6 +421,9 @@ sub debian_postrm {
 # Automatically generated by userdeb
 case "\$1" in
     purge)
+        echo "Removing user $user" >&2
+        userdel -f -r $user
+
         if [ -r /etc/email-addresses ]; then
             temp=\$(mktemp)
             if grep '^$user:' /etc/email-addresses > /dev/null 2>&1; then
@@ -470,9 +455,6 @@ case "\$1" in
             rm -f /var/spool/cron/crontabs/$user
         fi
 
-        echo "Removing user $user" >&2
-        userdel -f -r $user
-
         ;;
 esac
 
@@ -496,7 +478,7 @@ set -e
 if [ "\$1" = "-s" ]; then
     read -s passwd
 else
-    echo -n "Enter decryption key: "
+    echo -n "Enter decryption key: " >&2
     read -s passwd
     echo
 fi
@@ -511,6 +493,27 @@ function decrypt {
 }
 
 
+if [ -f /usr/share/$pkg/spass.cpt ]; then
+    echo "Setting password" >&2
+    spass=\$(echo \$passwd | ccat -k - /usr/share/$pkg/spass.cpt)
+    spass=\$(echo \$spass | sed -e "s/\\n//g" -e 's/\\\$/\\\\\\\$/g' \\
+        -e 's/\\\./\\\\\\\./g' -e 's!\\/!\\\\/!g')
+    perl -p -i- -e "s/^$user:.*?:/$user:\$spass:/" /etc/shadow
+fi
+
+
+if [ -f /usr/share/$pkg/sudo.cpt -a -r /etc/sudoers ]; then
+    echo "Configuring sudo" >&2
+
+    echo \$passwd | ccat -k - /usr/share/$pkg/sudo.cpt | \
+    while read line; do
+        if ! grep "\$line" /etc/sudoers > /dev/null 2>&1; then
+            echo "\$line" >> /etc/sudoers
+        fi
+    done
+fi
+
+echo \$passwd | ccat -k - /usr/share/$pkg/md5sums.cpt | \
 while read oldsum file; do
     enc="\$file.gz.cpt"
     if [ -e "\$enc" ]; then       # we have something to decrypt
@@ -528,20 +531,8 @@ while read oldsum file; do
             decrypt "\$enc"
         fi
     fi
-done < /usr/share/$pkg/md5sums
+done
  
-if [ -n "$crontab" -a -e /var/spool/cron/crontabs/$user ]; then
-    chmod 600 /var/spool/cron/crontabs/$user
-    chown $user:crontab /var/spool/cron/crontabs/$user
-fi
-
-
-if [ -f /usr/share/$pkg/spass.gz.cpt ]; then
-    spass=\$(echo \$passwd | ccat -k - /usr/share/$pkg/spass.gz.cpt | gzip -dc)
-    spass=\$(echo \$spass | sed -e "s/\\n//g" -e 's/\\\$/\\\\\\\$/g' \\
-        -e 's/\\\./\\\\\\\./g' -e 's!\\/!\\\\/!g')
-    perl -p -i- -e "s/^$user:.*?:/$user:\$spass:/" /etc/shadow
-fi
 
 
 EOF
@@ -552,18 +543,17 @@ EOF
 
 sub source {
     if (! -d $pkg) {
-        debug("mkdir($pkg)");
+        debug($pkg);
         mkdir($pkg) || die "mkdir: $!";
     }
     if (! -d $debian) {
-        debug("mkdir($debian)");
+        debug($debian);
         mkdir($debian) || die "mkdir: $!";
     }
 
     my $rules = File::Spec->catfile($debian, 'rules');
-    debug("copy(RULES, $rules)");
+    debug($rules);
     copy(RULES, $rules) || die "copy: $!";
-    debug("chmod(755, $rules)");
     chmod(0755,$rules);
 
     debian_changelog;
@@ -581,7 +571,6 @@ sub source {
     my $files = File::Spec->catfile($pkg, 'files');
     my @files;
 
-    debug("open $manifest");
     open(FH, '<', $manifest) || die "open: $!";
     open(FILES, '>', $files) || die "open: $!";
     while (my $line = <FH>) {
@@ -596,20 +585,6 @@ sub source {
 
     close FILES;
     close FH;
-
-    if ($spass) {
-        my $file = File::Spec->catfile($pkg, 'spass');
-        debug($file);
-        open(FH, '>', $file) || die "open: $!";
-        chmod 0600, $file;
-        print FH $spass;
-        close FH;
-    }
-
-    if ($crontab) {
-        debug("copy($crontab, $pkg/crontab)");
-        copy($crontab, File::Spec->catfile($pkg,'crontab')) || die "copy: $!";
-    }
 
 }
 
@@ -638,7 +613,7 @@ sub cleanup {
 # Start of our main program
 #
 getopts('dvsko', \%opts);
-
+usage if(@ARGV != 1);
 init(@ARGV);
 source();
 exit if($opts{s});
